# Generated by Django 5.2.17 on 2026-09-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('high school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('doctorate', 'Doctorate')], default='bachelors', max_length=20),
        ),
    ]
