# Generated by Django 5.2.17 on 2026-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_education_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='education',
            name='started_at',
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
