# Generated by Django 5.2.17 on 2026-09-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='issued_at',
            field=models.DateTimeField(),
        ),
    ]
