# Generated by Django 5.2.17 on 2026-09-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_certifications_issued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='issued_at',
            field=models.DateField(),
        ),
    ]
