# Generated by Django 5.2.17 on 2026-09-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_education_starred_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certifications',
            options={'permissions': [('can_create', 'Bisa menambahkan sertifikasi'), ('can_update', 'Bisa mengubah sertifikasi'), ('can_delete', 'Bisa menghapus sertifikasi')]},
        ),
    ]
