# Generated by Django 5.2.17 on 2026-09-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_certifications_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certifications',
            options={},
        ),
    ]
